//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_ACCOUNT_GROUP
    {
        public int COMP_CODE { get; set; }
        public string GROUP_CODE { get; set; }
        public string DESCL { get; set; }
        public string DESCA { get; set; }
        public string REMARKS { get; set; }
    }
}
