//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_ACCOUNT_YEAR
    {
        public int COMP_CODE { get; set; }
        public string ACC_CODE { get; set; }
        public int FIN_YEAR { get; set; }
        public Nullable<decimal> OPENING_BALANCE { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
        public Nullable<decimal> ACC_LIMIT { get; set; }
        public string REMARKS { get; set; }
    }
}
