//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_G_Vendor
    {
        public int VendorID { get; set; }
        public string VendorCode { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string NAMEA { get; set; }
        public string NAMEL { get; set; }
        public Nullable<byte> VATType { get; set; }
        public string VATNo { get; set; }
    }
}
