//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_LnkVoucher
    {
        public long ID { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> bracode { get; set; }
        public string System_Code { get; set; }
        public string Tr_Code { get; set; }
        public Nullable<long> TrID { get; set; }
        public Nullable<long> TrNo { get; set; }
        public Nullable<int> Serial { get; set; }
        public string Acc_Code { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string CC_Code { get; set; }
        public string Line_DescA { get; set; }
        public string Line_DescE { get; set; }
        public Nullable<int> Voucher_No { get; set; }
        public Nullable<int> SOURCE_TYPE { get; set; }
        public Nullable<int> TYPE_CODE { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
    }
}
