//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_RecPay_D_Category
    {
        public int CatID { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string CatCode { get; set; }
        public string Cat_DescA { get; set; }
        public string Cat_DescE { get; set; }
        public string REMARKS { get; set; }
        public string AccountCode { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string CodePrefex { get; set; }
        public string LastNumber { get; set; }
    }
}
