//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_RecPay_D_Accounts
    {
        public int ExpenseID { get; set; }
        public Nullable<int> TrType { get; set; }
        public Nullable<int> ExpCode { get; set; }
        public string ExpDescA { get; set; }
        public string ExpDescE { get; set; }
        public string ExpAccountCode { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
