//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Rec_D_DiscountPlanSegment
    {
        public int DiscountPlanSegmentID { get; set; }
        public Nullable<int> DiscountplanID { get; set; }
        public Nullable<decimal> YtoDMinLimit { get; set; }
        public Nullable<decimal> YtoDMaxLimit { get; set; }
        public Nullable<int> ItemCatID { get; set; }
        public Nullable<decimal> DiscountPrc { get; set; }
    }
}
