//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Rec_D_DiscountPlan
    {
        public int DiscountplanID { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<int> ApplyTo { get; set; }
        public Nullable<int> CoverType { get; set; }
    }
}
