//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_TmpVoucherProcess
    {
        public int id { get; set; }
        public string CurrentUserCode { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<int> COMP_CODE { get; set; }
        public Nullable<int> VOUCHER_CODE { get; set; }
        public Nullable<System.DateTime> VOUCHER_DATE { get; set; }
        public string VOUCHER_DESC { get; set; }
        public Nullable<int> VOUCHER_STATUS { get; set; }
        public Nullable<int> TYPE_CODE { get; set; }
        public string REF_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public string POSTED_BY { get; set; }
        public Nullable<System.DateTime> POSTED_AT { get; set; }
        public Nullable<int> SOURCE_TYPE { get; set; }
        public string VOUCHER_DATEH { get; set; }
        public string AUTHORISED_BY { get; set; }
        public Nullable<System.DateTime> AUTHORISED_AT { get; set; }
        public string TYPE_DESCA { get; set; }
        public string TYPE_DESCE { get; set; }
        public string St_DescE { get; set; }
        public string St_DescA { get; set; }
        public string Src_DescE { get; set; }
        public string Src_DescA { get; set; }
        public Nullable<int> voucherid { get; set; }
    }
}
