//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Voucher_Types
    {
        public int COMP_CODE { get; set; }
        public int VoucherType { get; set; }
        public int TYPE_CODE { get; set; }
        public string TYPE_DESCA { get; set; }
        public string TYPE_DESCE { get; set; }
        public string Remarks { get; set; }
    }
}
