//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQ_GetCashVoucherHeader
    {
        public Nullable<int> COMP_CODE { get; set; }
        public Nullable<int> VOUCHER_CODE { get; set; }
        public Nullable<System.DateTime> VOUCHER_DATE { get; set; }
        public string VOUCHER_DESC { get; set; }
        public Nullable<byte> VOUCHER_STATUS { get; set; }
        public Nullable<short> TYPE_CODE { get; set; }
        public string REF_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public string POSTED_BY { get; set; }
        public Nullable<System.DateTime> POSTED_AT { get; set; }
        public string TYPE_DESCA { get; set; }
        public string TYPE_DESCE { get; set; }
        public string St_DescE { get; set; }
        public string St_DescA { get; set; }
        public int VoucherID { get; set; }
        public Nullable<byte> TRType { get; set; }
        public Nullable<byte> CheckType { get; set; }
        public string BENIFICIARY { get; set; }
        public string ACC_CODE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string CHECK_CODE { get; set; }
        public string BANK { get; set; }
        public string DEPOSIT_ACC_CODE { get; set; }
        public Nullable<byte> CheckStatus { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string chkType_DescA { get; set; }
        public string chkType_DescE { get; set; }
        public string ACC_DESCA { get; set; }
        public string ACC_DESCL { get; set; }
    }
}
