//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQ_GetJournalDetail
    {
        public Nullable<int> COMP_CODE { get; set; }
        public Nullable<int> VOUCHER_CODE { get; set; }
        public Nullable<int> VOUCHER_SERIAL { get; set; }
        public string ACC_CODE { get; set; }
        public string CC_CODE { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public string DESCL { get; set; }
        public string DESCA { get; set; }
        public string CCDT_CODE { get; set; }
        public Nullable<int> INVOICE_NO { get; set; }
        public Nullable<int> BOOK_TR_NO { get; set; }
        public string SRC_SYSTEM_CODE { get; set; }
        public string SRC_SUB_SYSTEM_CODE { get; set; }
        public Nullable<int> SRC_BRA_CODE { get; set; }
        public string SRC_TR_CODE { get; set; }
        public Nullable<int> SRC_TR_NO { get; set; }
        public string SRC_TR_TYPE { get; set; }
        public Nullable<decimal> DEBIT_FC { get; set; }
        public Nullable<decimal> CREDIT_FC { get; set; }
        public string CC_DESCA { get; set; }
        public string CC_DESCE { get; set; }
        public string ACC_DESCA { get; set; }
        public string ACC_DESCL { get; set; }
        public int VoucherDetailID { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public string CCDT_TYPE { get; set; }
        public string CCDT_DESCA { get; set; }
        public string CCDT_DESCE { get; set; }
    }
}
