//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQ_GetAccountGroupDetail
    {
        public int COMP_CODE { get; set; }
        public string GROUP_CODE { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_DESCA { get; set; }
        public string ACC_DESCL { get; set; }
    }
}
