//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQ_GetAccount
    {
        public int COMP_CODE { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_DESCA { get; set; }
        public string ACC_DESCL { get; set; }
        public Nullable<short> ACC_GROUP { get; set; }
        public Nullable<short> ACC_TYPE { get; set; }
        public Nullable<short> ACC_LEVEL { get; set; }
        public Nullable<bool> ACC_ACTIVE { get; set; }
        public string PARENT_ACC { get; set; }
        public Nullable<bool> DETAIL { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public string CCDT_TYPE { get; set; }
        public string CUR_CODE { get; set; }
        public int FIN_YEAR { get; set; }
        public Nullable<decimal> OPENING_BALANCE { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
        public Nullable<decimal> ACC_LIMIT { get; set; }
        public string REMARKS { get; set; }
    }
}
