//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQVAT_GetPurReturn
    {
        public int InvoiceRetID { get; set; }
        public Nullable<int> TR_NO { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> TR_DATE { get; set; }
        public Nullable<short> TR_TYPE { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> InvoiceHeaderID { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string VENDOR_NAME { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> PAID { get; set; }
        public Nullable<int> JOURNAL_NO { get; set; }
        public Nullable<bool> CLOSED { get; set; }
        public Nullable<bool> CANCEL { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<bool> POSTED { get; set; }
        public Nullable<System.DateTime> ACTUAL_DATE { get; set; }
        public string PrntNo { get; set; }
        public string Ref_No { get; set; }
        public Nullable<int> Con_No { get; set; }
        public Nullable<int> Pay_No { get; set; }
        public Nullable<int> ConTyp { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> NetATax { get; set; }
        public Nullable<byte> VatType { get; set; }
        public Nullable<bool> VatApplied { get; set; }
        public Nullable<int> VndVatType { get; set; }
        public Nullable<decimal> DedTaxPrc { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<byte> SalesType { get; set; }
        public Nullable<bool> ImportInvoice { get; set; }
        public string PAY_ACC_CODE { get; set; }
        public string VendorCode { get; set; }
        public string vnd_NameA { get; set; }
        public string vnd_NameE { get; set; }
        public Nullable<int> Pur_Tr_No { get; set; }
        public string Pur_DocNo { get; set; }
        public Nullable<System.DateTime> Pur_TrDate { get; set; }
        public int PurHD_Serial { get; set; }
        public string PurHd_DocNo { get; set; }
    }
}
