//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQVAT_GetPurInvoiceHeader
    {
        public int InvoiceHeaderID { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Ref_No { get; set; }
        public string DocNo { get; set; }
        public Nullable<int> VendorID { get; set; }
        public int VND_SERIAL { get; set; }
        public Nullable<short> TR_TYPE { get; set; }
        public string VENDOR_NAME { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> PAID { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> NetATax { get; set; }
        public Nullable<bool> VatApplied { get; set; }
        public Nullable<int> VndVatType { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<byte> SalesType { get; set; }
        public string PAY_ACC_CODE { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CCDT_CODE { get; set; }
        public string ACC_DESCA { get; set; }
        public string ACC_DESCL { get; set; }
        public string vnd_NameA { get; set; }
        public string vnd_NameE { get; set; }
        public string VendorCode { get; set; }
    }
}
