//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQVAT_GetPeriodDetail
    {
        public int COMP_CODE { get; set; }
        public int VAT_YEAR { get; set; }
        public int PERIOD_CODE { get; set; }
        public short TYPE { get; set; }
        public short CODE { get; set; }
        public Nullable<decimal> Val_Amount { get; set; }
        public Nullable<decimal> Upd_Amount { get; set; }
        public Nullable<decimal> VAT_Amount { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> VatPerc { get; set; }
        public Nullable<int> LineOrder { get; set; }
    }
}
