//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVAT_CONTROL
    {
        public int COMP_CODE { get; set; }
        public int VAT_YEAR { get; set; }
        public Nullable<bool> VAT_SETTING { get; set; }
        public Nullable<byte> VAT_PERIOD { get; set; }
        public Nullable<System.DateTime> VAT_START_DATE { get; set; }
        public Nullable<System.DateTime> VAT_END_DATE { get; set; }
        public string VAT_CR_ACC { get; set; }
        public string VAT_DB_ACC { get; set; }
        public string VAT_ACCURUAL_ACC { get; set; }
        public Nullable<int> VAT_WARNING_DAYS { get; set; }
        public Nullable<int> VAT_ALLOWED_DAYS { get; set; }
        public Nullable<decimal> VAT_PREVBAL { get; set; }
        public string Sls_DISC_ACC_CODE { get; set; }
        public string Pur_DISC_ACC_CODE { get; set; }
    }
}
