//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVAT_TR_PurInvoice
    {
        public int InvoiceId { get; set; }
        public Nullable<int> TR_NO { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> TR_DATE { get; set; }
        public string PERSON { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> PAID { get; set; }
        public Nullable<int> JOURNAL_NO { get; set; }
        public Nullable<int> JOURNAL_RET_NO { get; set; }
        public Nullable<bool> CLOSED { get; set; }
        public Nullable<bool> CANCEL { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<System.DateTime> ACTUAL_DATE { get; set; }
        public string PrntNo { get; set; }
        public string Ref_No { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> NetATax { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<bool> ImportInvoice { get; set; }
        public string CCDT_CODE { get; set; }
    }
}
