//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVAT_TR_PurInvoiceDetail
    {
        public int InvoiceDetailID { get; set; }
        public Nullable<int> InvoiceHeaderID { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> TR_SERIAL { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> UomID { get; set; }
        public Nullable<decimal> SoldQty { get; set; }
        public Nullable<decimal> Unitprice { get; set; }
        public Nullable<decimal> DiscountPrc { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> NetUnitPrice { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public Nullable<int> VatApplied { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> NetAfterVat { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> ACTUAL_DATE { get; set; }
        public Nullable<decimal> QTY_RET { get; set; }
        public string CC_CODE { get; set; }
        public string CCDT_CODE { get; set; }
        public Nullable<int> VatNatID { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> VND_SERIAL { get; set; }
    }
}
