//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_LnkTransVoucher
    {
        public int COMP_CODE { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_CODE { get; set; }
        public string TR_CODE { get; set; }
        public int SERIAL { get; set; }
        public string VarCode { get; set; }
        public bool ISDebit { get; set; }
        public Nullable<int> AccType { get; set; }
        public string AccFixedCode { get; set; }
        public string AccVarCode { get; set; }
        public string AccBraCode { get; set; }
        public Nullable<int> CCType { get; set; }
        public string CCFixedCode { get; set; }
        public string CCVarCode { get; set; }
        public string CCBraCode { get; set; }
        public Nullable<bool> IsCollective { get; set; }
        public string LineRemarkA { get; set; }
        public string LineRemarkE { get; set; }
    }
}
