//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_LnkVarBranch
    {
        public int CompCode { get; set; }
        public int BraCode { get; set; }
        public string Lnktype { get; set; }
        public int Ser { get; set; }
        public string LnkCode { get; set; }
        public string GLAccountCode { get; set; }
        public string CC_Code { get; set; }
    }
}
