//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_LnkTransVariable
    {
        public string SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_CODE { get; set; }
        public string TR_CODE { get; set; }
        public string VarType { get; set; }
        public string VarCode { get; set; }
        public string Var_DESCA { get; set; }
        public string Var_DESCE { get; set; }
        public string FN_VarExpression { get; set; }
        public string DataSource { get; set; }
    }
}
