//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GQ_GetLnkTransComp
    {
        public string SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_CODE { get; set; }
        public string TR_CODE { get; set; }
        public string TR_DESCA { get; set; }
        public string TR_DESCE { get; set; }
        public Nullable<byte> VOUCHER_TYPE { get; set; }
        public Nullable<int> VOUCHER_SOURCE_TYPE { get; set; }
        public string TABLE_NAME { get; set; }
        public string TABLE_CONDITION { get; set; }
        public string FN_COMP_CODE { get; set; }
        public string FN_BRA_CODE { get; set; }
        public string FN_TR_ID { get; set; }
        public string FN_TR_NO { get; set; }
        public string FN_TR_TYPE { get; set; }
        public string FN_TR_DATE { get; set; }
        public string FN_USER { get; set; }
        public string FN_TR_AMOUNT { get; set; }
        public string FN_TR_DESCA { get; set; }
        public string FN_TR_DESCE { get; set; }
        public string FN_VOUCHER_CODE { get; set; }
        public Nullable<bool> INTEGRATE { get; set; }
        public string BASE_TABLE_NAME { get; set; }
        public string FN_POSTED { get; set; }
        public string COMP_CODE { get; set; }
        public Nullable<bool> Comp_INTEGRATE { get; set; }
        public Nullable<bool> IsView { get; set; }
    }
}
