//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GQ_GetRoleModule
    {
        public int RoleId { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_CODE { get; set; }
        public string MODULE_CODE { get; set; }
        public Nullable<bool> EXECUTE { get; set; }
        public Nullable<bool> CREATE { get; set; }
        public Nullable<bool> EDIT { get; set; }
        public Nullable<bool> DELETE { get; set; }
        public Nullable<bool> PRINT { get; set; }
        public Nullable<bool> VIEW { get; set; }
        public Nullable<bool> CUSTOM1 { get; set; }
        public Nullable<bool> CUSTOM2 { get; set; }
        public Nullable<bool> CUSTOM3 { get; set; }
        public Nullable<bool> CUSTOM4 { get; set; }
        public Nullable<bool> CUSTOM5 { get; set; }
        public Nullable<bool> CUSTOM6 { get; set; }
        public Nullable<bool> CUSTOM7 { get; set; }
        public Nullable<bool> CUSTOM8 { get; set; }
        public Nullable<bool> CUSTOM9 { get; set; }
        public Nullable<bool> ViewImages { get; set; }
        public Nullable<bool> EditImages { get; set; }
        public string MENU_NO { get; set; }
        public string MODULE_DESCE { get; set; }
        public string MODULE_DESCA { get; set; }
        public bool md_Create { get; set; }
        public bool md_edit { get; set; }
        public bool md_delete { get; set; }
        public bool md_print { get; set; }
        public bool md_view { get; set; }
        public bool md_custom1 { get; set; }
        public bool md_custom2 { get; set; }
        public bool md_custom3 { get; set; }
        public string CUSTOM1_DESC { get; set; }
        public string CUSTOM2_DESC { get; set; }
        public string CUSTOM3_DESC { get; set; }
        public Nullable<bool> md_custom4 { get; set; }
        public Nullable<bool> md_custom5 { get; set; }
        public Nullable<bool> md_custom6 { get; set; }
        public string CUSTOM4_DESC { get; set; }
        public string CUSTOM5_DESC { get; set; }
        public string CUSTOM6_DESC { get; set; }
        public Nullable<bool> md_custom7 { get; set; }
        public Nullable<bool> md_custom8 { get; set; }
        public Nullable<bool> md_custom9 { get; set; }
        public string CUSTOM7_DESC { get; set; }
        public string CUSTOM8_DESC { get; set; }
        public string CUSTOM9_DESC { get; set; }
        public Nullable<bool> AVAILABLE { get; set; }
        public string MODULE_TYPE { get; set; }
        public Nullable<bool> Images_Enabled { get; set; }
    }
}
