//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GQ_USERS
    {
        public string USER_CODE { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_NAME { get; set; }
        public bool USER_ACTIVE { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string JobTitle { get; set; }
        public Nullable<byte> USER_TYPE { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> SalesManID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Vnd_CompName { get; set; }
        public Nullable<int> CodeValue { get; set; }
        public string DescA { get; set; }
    }
}
