//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Period
    {
        public int CompCode { get; set; }
        public int FinYear { get; set; }
        public int PERIOD_CODE { get; set; }
        public string PERIOD_DESC { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<bool> FixQty { get; set; }
        public Nullable<bool> FixCost { get; set; }
        public int Status { get; set; }
        public string Closed_BY { get; set; }
        public Nullable<System.DateTime> Closed_AT { get; set; }
        public string ReOpen_BY { get; set; }
        public Nullable<System.DateTime> ReOpen_AT { get; set; }
    }
}
