//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_PeriodItem
    {
        public int CompCode { get; set; }
        public int FinYear { get; set; }
        public int PERIOD_CODE { get; set; }
        public int Storeid { get; set; }
        public int ItemID { get; set; }
        public Nullable<decimal> StartQty { get; set; }
        public Nullable<decimal> StartCost { get; set; }
        public Nullable<decimal> PurchaseQty { get; set; }
        public Nullable<decimal> PurchaseValue { get; set; }
        public Nullable<decimal> SalesQty { get; set; }
        public Nullable<decimal> SalesValue { get; set; }
        public Nullable<decimal> TFQty { get; set; }
        public Nullable<decimal> AdjQty { get; set; }
        public Nullable<decimal> AdjCost { get; set; }
        public Nullable<decimal> CloseBalance { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
        public Nullable<decimal> ProdQty { get; set; }
        public Nullable<decimal> ProdValue { get; set; }
        public Nullable<decimal> ProdusedQty { get; set; }
        public Nullable<decimal> IssueQty { get; set; }
        public Nullable<decimal> TFINQty { get; set; }
        public Nullable<decimal> TFINCost { get; set; }
    }
}
