//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_TR_OperationSalesman
    {
        public int OperationSalesmanID { get; set; }
        public int OperationID { get; set; }
        public Nullable<int> SalesmanId { get; set; }
        public Nullable<decimal> Close_TotalSalesCash { get; set; }
        public Nullable<decimal> Close_TotalSalesCashVAT { get; set; }
        public Nullable<decimal> Close_TotalSalesCredit { get; set; }
        public Nullable<decimal> Close_TotalSalesCreditVAT { get; set; }
        public Nullable<decimal> Close_CashOnhand { get; set; }
        public Nullable<decimal> Close_CashOnBank { get; set; }
        public Nullable<decimal> Close_TotalSales { get; set; }
    }
}
