//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_TR_OperationItems
    {
        public int OperationItemID { get; set; }
        public int OperationID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> SoldQty { get; set; }
        public Nullable<decimal> ScrapQty { get; set; }
        public Nullable<decimal> Est_CostPrice { get; set; }
        public Nullable<decimal> Est_SalesPrice { get; set; }
        public Nullable<decimal> Min_SalesPrice { get; set; }
        public Nullable<decimal> OnhandQty { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public Nullable<decimal> Close_SoldQty { get; set; }
        public Nullable<decimal> Close_ScrapQty { get; set; }
        public Nullable<decimal> Close_OnhandQty { get; set; }
        public Nullable<decimal> Close_TotalSales { get; set; }
    }
}
