//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetPurReceiveChargeSum
    {
        public int ReceiveID { get; set; }
        public Nullable<decimal> TotAdd { get; set; }
        public Nullable<decimal> TotAddVat { get; set; }
        public Nullable<decimal> TotAddAfterVat { get; set; }
    }
}
