//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetStkAdjustDetail
    {
        public int AdjustDetailID { get; set; }
        public Nullable<int> AdjustID { get; set; }
        public Nullable<int> Serial { get; set; }
        public string BarCode { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ItemStoreBatchid { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> CountQty { get; set; }
        public Nullable<decimal> OnhandQty { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> NewUnitCost { get; set; }
        public Nullable<decimal> StkUnitCost { get; set; }
        public Nullable<decimal> NewStkUnitCost { get; set; }
        public Nullable<decimal> StockCountedQty { get; set; }
        public Nullable<decimal> StockOnhandQty { get; set; }
        public Nullable<decimal> DiffQty { get; set; }
        public Nullable<decimal> StockDiffQty { get; set; }
        public string ItemCode { get; set; }
        public string itm_DescA { get; set; }
        public string itm_DescE { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string Uom_DescA { get; set; }
        public string UOM_DescE { get; set; }
        public string UomCode { get; set; }
    }
}
