//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetItemStoreInfo
    {
        public int ItemID { get; set; }
        public string ItemCode { get; set; }
        public string Itm_DescA { get; set; }
        public Nullable<int> UomID { get; set; }
        public int ItemFamilyID { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string RefItemCode { get; set; }
        public Nullable<System.DateTime> FirstEntryDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> LastBarCodeSeq { get; set; }
        public string BarCodePrefix { get; set; }
        public Nullable<int> StoreCode { get; set; }
        public Nullable<int> BraCode { get; set; }
        public string LOCATION { get; set; }
        public Nullable<decimal> OnhandQty { get; set; }
        public Nullable<decimal> MinQty { get; set; }
        public Nullable<decimal> MaxQty { get; set; }
        public Nullable<decimal> StartQty { get; set; }
        public string Uom_DescA { get; set; }
        public string Uom_DescE { get; set; }
        public string FamilyCode { get; set; }
        public string Family_DescA { get; set; }
        public string Family_DescE { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<decimal> MinUnitPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> StarGlobalCost { get; set; }
        public Nullable<decimal> GlobalCost { get; set; }
        public Nullable<decimal> UnitWholePrice { get; set; }
        public Nullable<decimal> MinUnitWholePrice { get; set; }
        public int ItemYearID { get; set; }
        public int ItemStoreID { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<int> VatNatID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ISSales { get; set; }
        public Nullable<bool> IsStock { get; set; }
        public Nullable<bool> IsProduct { get; set; }
        public Nullable<bool> IsPurchase { get; set; }
        public Nullable<decimal> StartLocalCost { get; set; }
        public Nullable<decimal> LocalCost { get; set; }
    }
}
