//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetPurChargeInfo
    {
        public Nullable<int> VatType { get; set; }
        public int ChargeID { get; set; }
        public int CompCode { get; set; }
        public Nullable<int> CostAddCode { get; set; }
        public string DESCA { get; set; }
        public string DESCL { get; set; }
        public Nullable<bool> IsAddition { get; set; }
        public Nullable<decimal> DefaultPerc { get; set; }
        public Nullable<bool> IsAffectPurchaseCost { get; set; }
        public string GLExpenseAcc { get; set; }
        public short Ch_VatType { get; set; }
        public Nullable<decimal> VatPerc { get; set; }
    }
}
