//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetStkOpenDetail
    {
        public int OpenDetailID { get; set; }
        public Nullable<int> OpenID { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ItemStoreBatchid { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> StkUnitCost { get; set; }
        public string UomCode { get; set; }
        public string uom_DescA { get; set; }
        public string Uom_DescE { get; set; }
        public string ItemCode { get; set; }
        public string DescA { get; set; }
        public string DescL { get; set; }
    }
}
