//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetBoxAdjustmentVat
    {
        public int AdustmentTypeID { get; set; }
        public Nullable<int> AdjCode { get; set; }
        public string Adj_DescA { get; set; }
        public string Adj_DescE { get; set; }
        public Nullable<int> VatType { get; set; }
        public string AccountCode { get; set; }
        public Nullable<bool> IsDebit { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public string Vat_Desc { get; set; }
        public Nullable<decimal> VatPerc { get; set; }
        public Nullable<int> CompCode { get; set; }
    }
}
