//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetCollectList
    {
        public int CollectID { get; set; }
        public Nullable<int> TrNo { get; set; }
        public string RefNO { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string TrDateH { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> VoucherNo { get; set; }
        public Nullable<byte> VoucherType { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> LabourCost { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<decimal> InputItemCost { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> NewUnitCost { get; set; }
        public Nullable<decimal> OutValue { get; set; }
        public string ItemCode { get; set; }
        public string Itm_DescA { get; set; }
        public string Itm_DescE { get; set; }
        public string UomCode { get; set; }
        public string Uom_DescA { get; set; }
        public string Uom_DescE { get; set; }
        public int ItemFamilyID { get; set; }
        public string FamilyCode { get; set; }
        public string fmly_DescA { get; set; }
        public string fmly_DescE { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> TrType { get; set; }
        public string Typ_DescA { get; set; }
        public string Typ_DescE { get; set; }
    }
}
