//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetCollectDetail
    {
        public int CollectDetailID { get; set; }
        public Nullable<int> CollectID { get; set; }
        public Nullable<bool> IsInput { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> OnhandQty { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> NewUnitCost { get; set; }
        public Nullable<decimal> StkUnitCost { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<decimal> StockOnhandQty { get; set; }
        public Nullable<decimal> CostFactorPrc { get; set; }
        public Nullable<decimal> NewStockUnitCost { get; set; }
        public string ItemCode { get; set; }
        public string itm_DescA { get; set; }
        public string itm_DescE { get; set; }
        public string UomCode { get; set; }
        public string u_DescA { get; set; }
        public string u_DescE { get; set; }
    }
}
