//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetOperationItemInfo
    {
        public string ItemCode { get; set; }
        public string Itm_DescA { get; set; }
        public string Itm_DescE { get; set; }
        public Nullable<int> UomID { get; set; }
        public int ItemFamilyID { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string RefItemCode { get; set; }
        public Nullable<System.DateTime> FirstEntryDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> LastBarCodeSeq { get; set; }
        public string BarCodePrefix { get; set; }
        public Nullable<decimal> OnhandQty { get; set; }
        public string Uom_DescA { get; set; }
        public string Uom_DescE { get; set; }
        public string FamilyCode { get; set; }
        public string Family_DescA { get; set; }
        public string Family_DescE { get; set; }
        public Nullable<int> CatID { get; set; }
        public int OperationItemID { get; set; }
        public int OperationID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> SoldQty { get; set; }
        public Nullable<decimal> ScrapQty { get; set; }
        public Nullable<decimal> Est_CostPrice { get; set; }
        public Nullable<decimal> Est_SalesPrice { get; set; }
        public Nullable<decimal> Min_SalesPrice { get; set; }
        public string Expr1 { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public Nullable<decimal> Close_SoldQty { get; set; }
        public Nullable<decimal> Close_ScrapQty { get; set; }
        public Nullable<decimal> Close_OnhandQty { get; set; }
        public Nullable<decimal> Close_TotalSales { get; set; }
    }
}
