//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetPurchaseOrderDetail
    {
        public int PurOrderDetailsID { get; set; }
        public Nullable<int> PurOrderID { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> POStockQty { get; set; }
        public Nullable<decimal> POQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> NetUnitCost { get; set; }
        public Nullable<decimal> BonusQty { get; set; }
        public Nullable<decimal> StockAvailableQty { get; set; }
        public Nullable<decimal> StockUnitCost { get; set; }
        public Nullable<decimal> TotRecQty { get; set; }
        public string ItemCode { get; set; }
        public string itm_DescA { get; set; }
        public string itm_DescE { get; set; }
        public string FamilyCode { get; set; }
        public string Fm_DescA { get; set; }
        public string Fm_DescE { get; set; }
        public string UomCode { get; set; }
        public string Uom_DescA { get; set; }
        public string UOM_DescE { get; set; }
    }
}
