//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetStkIssueCC
    {
        public int IssueToCcID { get; set; }
        public Nullable<int> Tr_No { get; set; }
        public Nullable<int> TRType { get; set; }
        public string CC_CODE { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> RefTRID { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> IssueTypeID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string TrDateH { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> VoucherNo { get; set; }
        public Nullable<byte> VoucherType { get; set; }
        public string IssuedBy { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> STORE_CODE { get; set; }
        public string store_DescA { get; set; }
        public string Store_DescE { get; set; }
        public string CC_DESCA { get; set; }
        public string CC_DESCE { get; set; }
        public string Type_DescA { get; set; }
        public string Type_DescE { get; set; }
        public string GL_Acc_Code { get; set; }
    }
}
