//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetOperationSalesmanItem
    {
        public int OperationSalesmanItemID { get; set; }
        public Nullable<int> OperationSalesmanID { get; set; }
        public Nullable<int> OperationItemID { get; set; }
        public Nullable<int> OperationID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> SoldQty { get; set; }
        public Nullable<decimal> ScrapQty { get; set; }
        public Nullable<decimal> OnhandQty { get; set; }
        public string ItemCode { get; set; }
        public string IT_DescA { get; set; }
        public string IT_DescE { get; set; }
        public string FamilyCode { get; set; }
        public string FamDescA { get; set; }
        public string Fam_DescE { get; set; }
        public Nullable<int> SalesmanId { get; set; }
        public Nullable<decimal> Min_SalesPrice { get; set; }
        public Nullable<decimal> Est_SalesPrice { get; set; }
        public Nullable<decimal> Est_CostPrice { get; set; }
        public int VatNatID { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
    }
}
