//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetStkIssueCCDetail
    {
        public int IssueToCcDetailID { get; set; }
        public Nullable<int> IssueToCcID { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> ReqQty { get; set; }
        public Nullable<decimal> IssueQty { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> IssueedBeforeQty { get; set; }
        public Nullable<decimal> TotRetQty { get; set; }
        public string ItemCode { get; set; }
        public string itm_DescA { get; set; }
        public string itm_DescE { get; set; }
        public string uom_DescA { get; set; }
        public string UomCode { get; set; }
        public string uom_DescE { get; set; }
    }
}
