//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetBoxReceiveList
    {
        public int ReceiptID { get; set; }
        public Nullable<int> CashBoxID { get; set; }
        public Nullable<int> TrType { get; set; }
        public Nullable<int> RecPayTypeId { get; set; }
        public Nullable<int> TrNo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string TrDateH { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> FromCashBoxID { get; set; }
        public Nullable<int> ExpenseID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<decimal> CardAmount { get; set; }
        public string BankAccountCode { get; set; }
        public string ReceiptDescA { get; set; }
        public string ReceiptDescE { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> VoucherNo { get; set; }
        public Nullable<byte> VoucherType { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string CustomerCODE { get; set; }
        public string cus_NameA { get; set; }
        public string cus_NameE { get; set; }
        public string Bank_Acc_DescA { get; set; }
        public string Bank_ACC_DescE { get; set; }
        public string CashBox_DescA { get; set; }
        public string CashBox_DescE { get; set; }
        public string VendorCode { get; set; }
        public string Ven_NameA { get; set; }
        public string Ven_NameE { get; set; }
        public Nullable<int> ExpCode { get; set; }
        public string Exp_DescA { get; set; }
        public string Exp_DescE { get; set; }
        public Nullable<int> Bef_ID { get; set; }
        public Nullable<int> Bef_Code { get; set; }
        public string Bef_DescA { get; set; }
        public string Bef_DescE { get; set; }
        public string Type_DescA { get; set; }
        public string Type_DescE { get; set; }
        public string CashT_DescA { get; set; }
        public string CashT_DescE { get; set; }
        public string CheckNo { get; set; }
        public string TransferNo { get; set; }
        public string BankName { get; set; }
        public string BankAcc_Code { get; set; }
        public Nullable<bool> IsDeffered { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> CashType { get; set; }
        public string Bnk_acc_DescE { get; set; }
        public string ACC_DESCL { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<int> ChargeProviderID { get; set; }
        public Nullable<decimal> ChargesVat { get; set; }
        public Nullable<decimal> ChargeWithVat { get; set; }
        public Nullable<int> ChargeVatType { get; set; }
        public Nullable<decimal> ChargesVatPrc { get; set; }
        public string ProviderName { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public string ProviderVatNo { get; set; }
        public Nullable<int> ProviderVatType { get; set; }
        public Nullable<int> ProviderVatPrc { get; set; }
        public Nullable<decimal> ProviderVatAmount { get; set; }
        public string ProviderInvoiceNo { get; set; }
        public Nullable<System.DateTime> ProviderIndDate { get; set; }
        public Nullable<decimal> ProviderAmountBeforeVat { get; set; }
        public string CC_Code { get; set; }
        public string ChrgPrv_NameA { get; set; }
        public string Chrgprv_NameE { get; set; }
        public string Prov_Code { get; set; }
        public string Prov_NameA { get; set; }
        public string Prov_NameE { get; set; }
        public string ChargeInvoiceNo { get; set; }
    }
}
