//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_ItemCollect1
    {
        public string ItemDescA { get; set; }
        public Nullable<decimal> SoldQty { get; set; }
        public Nullable<decimal> Unitprice { get; set; }
        public Nullable<int> SalesManID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Remark { get; set; }
        public int InvoiceID { get; set; }
    }
}
