//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sls_InvoiceItem
    {
        public int InvoiceItemID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescA { get; set; }
        public Nullable<decimal> SoldQty { get; set; }
        public Nullable<decimal> Unitprice { get; set; }
        public Nullable<decimal> DiscountPrc { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> NetUnitPrice { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> NetAfterVat { get; set; }
        public Nullable<int> VatApplied { get; set; }
        public Nullable<decimal> TotRetQty { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> SalesManID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<decimal> ItemNetAmount { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Remark { get; set; }
    }
}
