//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Invoices
    {
        public string Vnd_Name { get; set; }
        public string Vnd_Mobile { get; set; }
        public string Vnd_Company { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> CommitionAmount { get; set; }
        public Nullable<int> Status { get; set; }
        public int VendorID { get; set; }
    }
}
