//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vnd_Inv_SlsMan
    {
        public string SalesmanCode { get; set; }
        public string SlsMan_Name { get; set; }
        public string SlsMan_IDNO { get; set; }
        public string SlsMan_Mobile { get; set; }
        public Nullable<bool> SlsMan_Active { get; set; }
        public string SlsMan_UserName { get; set; }
        public string VendorCode { get; set; }
        public string Vnd_Name { get; set; }
        public string Vnd_Mobile { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> Vnd_Active { get; set; }
        public string REMARKS { get; set; }
        public string Vnd_UserNAME { get; set; }
        public string Vnd_IDNO { get; set; }
        public int InvoiceID { get; set; }
        public Nullable<int> TrNo { get; set; }
        public string RefNO { get; set; }
        public Nullable<int> RefTrID { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string TrDateH { get; set; }
        public Nullable<int> TrType { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobile1 { get; set; }
        public string CustomerMobile2 { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public Nullable<int> SalesmanId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<int> VatType { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> DiscountPrc { get; set; }
        public Nullable<decimal> NetAfterVat { get; set; }
        public decimal CommitionAmount { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<decimal> CardAmount { get; set; }
        public Nullable<decimal> RemainAmount { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.TimeSpan> TrTime { get; set; }
        public string QRCode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> DeliveryEndDate { get; set; }
        public string PromoCode { get; set; }
        public Nullable<decimal> ChargeAmount { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public Nullable<int> LineCount { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string ZoneCode { get; set; }
        public string DescA { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Sls_ZoneID { get; set; }
        public string Zone_Remarks { get; set; }
        public Nullable<int> Inv_SlsManID { get; set; }
        public Nullable<int> Inv_VendorID { get; set; }
    }
}
